### PR TITLE
chore: generalized inventory handler/add dashboard dataset

### PR DESCRIPTION
**Pull request by jjfrench**
- adds icesat2 boreal biomass reduced resolution browse for STAC
- generalizes inventory handler for additional metadata files (renames csv key to user provided)

### CODE REVIEW

**Review by omshinde — APPROVED** [review]

**Review by emileten — APPROVED** [review]
could you write a quick description of your PR @jjfrench ? thanks !

**Comment by emileten** [comment]
@jjfrench I assume this was deployed both to test and dev ?

**Comment by emileten** [comment]
Ok just saw that it's not the case. Doing it rn.

**Comment by emileten** [comment]
Done ✅

**Pull request merged**
