### PR TITLE
Feat/additional datasets

### PR DESCRIPTION
**Pull request by jjfrench**
- ABoVE_UAVSAR_PALSAR.json
- AFRISAR_DLR2.json
- AfriSAR_UAVSAR_Geocoded_Covariance.json
- AfriSAR_UAVSAR_Geocoded_SLC.json
- AfriSAR_UAVSAR_KZ.json
- AfriSAR_UAVSAR_Normalization_Area.json
- AfriSAR_UAVSAR_Ungeocoded_Covariance.json
- Global_Forest_Change_2000-2017.json
- Global_PALSAR2_PALSAR_FNF.json
- Global_PALSAR2_PALSAR_Mosiac.json

### CODE REVIEW

**Comment by emileten** [comment]
Thanks, also for adding the `links` and `item_assets` fields. I will add those in the other later my day.

**Review by emileten — APPROVED** [review]
I pushed a commit that does further cleanup (removing VEDA jsons, adding links/item_assets empty fields).

**Comment by jjfrench** [comment]
Do we need to add "dashboard:is_periodic": false, "dashboard:time_density": null to each collection still?

**Comment by emileten** [comment]
No we don't @jjfrench. Let's remove it since it's not used in MAAP.

**Pull request merged**
